spring.application.name=Student
# Oracle DB Connection
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=MYVINOD
spring.datasource.password=SYSTEM
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA Config
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL (optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true